#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import shutil
from pathlib import Path
from typing import Any

try:
    from PIL import Image, ImageChops, ImageDraw, ImageOps
except ImportError as exc:  # pragma: no cover - exercised by runtime environment
    raise SystemExit("Pillow is required: python -m pip install Pillow") from exc


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a TN3K manual review packet from low-Dice curation queue.")
    parser.add_argument("--dataset-root", required=True, help="Dataset503 root containing imagesTs/labelsTs.")
    parser.add_argument("--prediction-dir", required=True, help="Prediction folder containing case_id.png files.")
    parser.add_argument("--queue-csv", required=True, help="manual_review_queue.csv generated by curation.")
    parser.add_argument("--output-dir", required=True, help="Review packet output directory.")
    parser.add_argument("--limit", type=int, default=20)
    parser.add_argument("--offset", type=int, default=0)
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    summary = build_packet(
        dataset_root=Path(args.dataset_root),
        prediction_dir=Path(args.prediction_dir),
        queue_csv=Path(args.queue_csv),
        output_dir=Path(args.output_dir),
        limit=args.limit,
        offset=args.offset,
        overwrite=args.overwrite,
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


def build_packet(
    *,
    dataset_root: Path,
    prediction_dir: Path,
    queue_csv: Path,
    output_dir: Path,
    limit: int,
    offset: int,
    overwrite: bool,
) -> dict[str, Any]:
    images_dir = dataset_root / "imagesTs"
    labels_dir = dataset_root / "labelsTs"
    for path in (images_dir, labels_dir, prediction_dir, queue_csv):
        if not path.exists():
            raise SystemExit(f"required input not found: {path}")
    if limit <= 0:
        raise SystemExit("--limit must be positive")
    if offset < 0:
        raise SystemExit("--offset must be non-negative")
    if output_dir.exists():
        if not overwrite:
            raise SystemExit(f"{output_dir} already exists; pass --overwrite")
        shutil.rmtree(output_dir)

    rows = read_queue(queue_csv)
    selected = rows[offset : offset + limit]
    if not selected:
        raise SystemExit("selected queue slice is empty")

    for name in ("cases", "panels"):
        (output_dir / name).mkdir(parents=True, exist_ok=True)

    packet_rows = []
    panel_paths = []
    for index, row in enumerate(selected, start=offset + 1):
        case_id = row["case_id"]
        case_dir = output_dir / "cases" / case_id
        case_dir.mkdir(parents=True, exist_ok=True)
        image_path = images_dir / f"{case_id}_0000.png"
        label_path = labels_dir / f"{case_id}.png"
        pred_path = prediction_dir / f"{case_id}.png"
        for path in (image_path, label_path, pred_path):
            if not path.is_file():
                raise SystemExit(f"case file not found for {case_id}: {path}")

        generated = render_case(case_id, image_path, label_path, pred_path, case_dir)
        panel_path = output_dir / "panels" / f"{case_id}_panel.png"
        shutil.copy2(generated["panel_path"], panel_path)
        panel_paths.append(panel_path)

        packet_rows.append(
            {
                **row,
                "queue_rank": index,
                "review_decision": "",
                "corrected_mask_path": "",
                "reviewer": "",
                "reviewed_at": "",
                "notes": "",
                "case_panel": rel(panel_path, output_dir),
                "original_image": rel(Path(generated["original_path"]), output_dir),
                "gt_overlay": rel(Path(generated["gt_overlay_path"]), output_dir),
                "prediction_overlay": rel(Path(generated["pred_overlay_path"]), output_dir),
                "comparison_overlay": rel(Path(generated["comparison_overlay_path"]), output_dir),
            }
        )

    contact_sheet = output_dir / "tn3k_manual_review_contact_sheet.png"
    make_contact_sheet(panel_paths, contact_sheet)
    packet_csv = output_dir / "manual_review_queue_first20.csv"
    write_packet_csv(packet_csv, packet_rows)
    packet_md = output_dir / "manual_review_packet.md"
    write_packet_markdown(packet_md, packet_rows, contact_sheet, output_dir)

    summary = {
        "dataset_root": str(dataset_root),
        "prediction_dir": str(prediction_dir),
        "queue_csv": str(queue_csv),
        "output_dir": str(output_dir),
        "offset": offset,
        "limit": limit,
        "selected_cases": len(packet_rows),
        "case_ids": [row["case_id"] for row in packet_rows],
        "category_counts": count_by(packet_rows, "category"),
        "primary_group_counts": count_by(packet_rows, "primary_group"),
        "artifacts": {
            "packet_csv": str(packet_csv),
            "packet_markdown": str(packet_md),
            "contact_sheet": str(contact_sheet),
        },
    }
    (output_dir / "packet_summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    return summary


def read_queue(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    required = {"case_id", "dice", "iou", "category", "primary_group", "suggested_action"}
    if not rows:
        raise SystemExit("queue is empty")
    missing = required.difference(rows[0].keys())
    if missing:
        raise SystemExit(f"queue missing columns: {', '.join(sorted(missing))}")
    return rows


def render_case(case_id: str, image_path: Path, label_path: Path, pred_path: Path, case_dir: Path) -> dict[str, str]:
    image = Image.open(image_path).convert("L")
    base = ImageOps.autocontrast(image).convert("RGB")
    label = binary_mask(Image.open(label_path).convert("L"))
    pred = binary_mask(Image.open(pred_path).convert("L"))
    if label.size != base.size:
        raise SystemExit(f"label size mismatch for {case_id}: {label.size} != {base.size}")
    if pred.size != base.size:
        raise SystemExit(f"prediction size mismatch for {case_id}: {pred.size} != {base.size}")

    original_path = case_dir / f"{case_id}_original.png"
    gt_overlay_path = case_dir / f"{case_id}_gt_overlay.png"
    pred_overlay_path = case_dir / f"{case_id}_prediction_overlay.png"
    comparison_overlay_path = case_dir / f"{case_id}_comparison_overlay.png"
    panel_path = case_dir / f"{case_id}_panel.png"

    base.save(original_path)
    overlay_mask(base, label, (230, 30, 30), 0.45).save(gt_overlay_path)
    overlay_mask(base, pred, (30, 190, 80), 0.45).save(pred_overlay_path)
    render_comparison(base, label, pred).save(comparison_overlay_path)
    make_case_panel(
        case_id,
        [
            ("Original", base),
            ("GT", Image.open(gt_overlay_path).convert("RGB")),
            ("Prediction", Image.open(pred_overlay_path).convert("RGB")),
            ("GT red / Pred green", Image.open(comparison_overlay_path).convert("RGB")),
        ],
        panel_path,
    )

    return {
        "original_path": str(original_path),
        "gt_overlay_path": str(gt_overlay_path),
        "pred_overlay_path": str(pred_overlay_path),
        "comparison_overlay_path": str(comparison_overlay_path),
        "panel_path": str(panel_path),
    }


def binary_mask(mask: Image.Image) -> Image.Image:
    return mask.point(lambda value: 255 if value > 0 else 0).convert("L")


def overlay_mask(base: Image.Image, mask: Image.Image, color: tuple[int, int, int], alpha: float) -> Image.Image:
    overlay = Image.new("RGB", base.size, color)
    blended = Image.blend(base, overlay, alpha)
    result = base.copy()
    result.paste(blended, mask=mask)
    return result


def render_comparison(base: Image.Image, gt: Image.Image, pred: Image.Image) -> Image.Image:
    gt_only = ImageChops.subtract(gt, pred)
    pred_only = ImageChops.subtract(pred, gt)
    overlap = ImageChops.multiply(gt, pred)
    result = base.copy()
    result = overlay_mask(result, gt_only, (230, 30, 30), 0.55)
    result = overlay_mask(result, pred_only, (30, 190, 80), 0.55)
    result = overlay_mask(result, overlap, (245, 210, 40), 0.60)
    return result


def make_case_panel(case_id: str, images: list[tuple[str, Image.Image]], output_path: Path) -> None:
    cell_w, cell_h, header_h = 256, 256, 24
    panel = Image.new("RGB", (cell_w * len(images), cell_h + header_h), "white")
    draw = ImageDraw.Draw(panel)
    for index, (title, image) in enumerate(images):
        thumb = fit_image(image, cell_w, cell_h)
        x = index * cell_w
        draw.text((x + 8, 6), f"{case_id} | {title}" if index == 0 else title, fill=(20, 20, 20))
        panel.paste(thumb, (x, header_h))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    panel.save(output_path)


def fit_image(image: Image.Image, width: int, height: int) -> Image.Image:
    copy = image.copy()
    copy.thumbnail((width, height), Image.Resampling.LANCZOS)
    canvas = Image.new("RGB", (width, height), "black")
    canvas.paste(copy, ((width - copy.width) // 2, (height - copy.height) // 2))
    return canvas


def make_contact_sheet(panel_paths: list[Path], output_path: Path) -> None:
    panels = [Image.open(path).convert("RGB") for path in panel_paths]
    cols = 1 if len(panels) <= 5 else 2
    gap = 12
    cell_w = max(panel.width for panel in panels)
    cell_h = max(panel.height for panel in panels)
    rows = (len(panels) + cols - 1) // cols
    sheet = Image.new("RGB", (cols * cell_w + (cols + 1) * gap, rows * cell_h + (rows + 1) * gap), "white")
    for index, panel in enumerate(panels):
        col = index % cols
        row = index // cols
        sheet.paste(panel, (gap + col * (cell_w + gap), gap + row * (cell_h + gap)))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(output_path)


def write_packet_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    fieldnames = [
        "queue_rank",
        "case_id",
        "dice",
        "iou",
        "category",
        "primary_group",
        "suggested_action",
        "review_decision",
        "corrected_mask_path",
        "reviewer",
        "reviewed_at",
        "notes",
        "case_panel",
        "original_image",
        "gt_overlay",
        "prediction_overlay",
        "comparison_overlay",
    ]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_packet_markdown(path: Path, rows: list[dict[str, Any]], contact_sheet: Path, output_dir: Path) -> None:
    lines = [
        "# TN3K Manual Review Packet",
        "",
        f"- Cases: `{len(rows)}`",
        f"- Contact sheet: `{rel(contact_sheet, output_dir)}`",
        "",
        f"![contact sheet]({rel(contact_sheet, output_dir)})",
        "",
        "| Rank | Case | Dice | Category | Group | Suggested action | Panel |",
        "| ---: | --- | ---: | --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            "| {rank} | `{case_id}` | {dice} | `{category}` | `{group}` | `{action}` | [panel]({panel}) |".format(
                rank=row["queue_rank"],
                case_id=row["case_id"],
                dice=round(float(row["dice"]), 4),
                category=row["category"],
                group=row["primary_group"],
                action=row["suggested_action"],
                panel=row["case_panel"],
            )
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def count_by(rows: list[dict[str, Any]], key: str) -> dict[str, int]:
    counts: dict[str, int] = {}
    for row in rows:
        value = row.get(key, "")
        counts[value] = counts.get(value, 0) + 1
    return dict(sorted(counts.items()))


def rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


if __name__ == "__main__":
    raise SystemExit(main())
